name = "spend"
compatibility_date = "2026-09-21"
main = ".svelte-kit/cloudflare/_worker.js"
workers_dev = false

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[[routes]]
pattern = "spending.bate.dev"
custom_domain = true
